### ISSUE TITLE
Could not pass event EntityPickupItemEvent to XPWars v1.1

### ISSUE THREAD

**Issue by Seff300** [notfoundname/XPWars#1]
Minecraft version: 1.16.1
Server software: Paper 1.16.1

This error happens when picking up items whilst playing a BedWars game
https://pastebin.com/qj2WfFPf

**Comment by notfoundname** [comment]
Hello, thanks for reporting the bug! Can you please update to latest build and test it again? https://ci.screamingsandals.org/job/XPWars/

**Comment by notfoundname** [comment]
try that build. https://github.com/notfoundname/XPWars/files/5049398/XPWars-1.5-SNAPSHOT-null.zip

**Comment by notfoundname** [comment]
Wait when ScreamingSandals will finish their new repository
